# Generated by Django 4.2.11 on 2024-03-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reportParagraph", models.TextField()),
                ("reportModelPrediction", models.CharField(max_length=20)),
                (
                    "reportUserPrediction",
                    models.CharField(
                        choices=[
                            ("", "Choose a Category"),
                            ("Business", "Business"),
                            ("Entertainment", "Entertainment"),
                            ("Politics", "Politics"),
                            ("Sports", "Sports"),
                            ("Technology", "Technology"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reportURL", models.URLField(blank=True)),
                ("reportComment", models.TextField(blank=True)),
                ("reportTime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
