# Generated by Django 4.2.11 on 2024-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inputPara", models.TextField()),
                ("firstCat", models.CharField(max_length=20)),
                ("seconCat", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "secondPercentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
            ],
        ),
    ]
